#aliases

# fancy completion
autoload compinit && compinit
zstyle ':completion:*' menu select
#zstyle ':completion:*' list-colors ''
RPROMPT="[%T]"

alias ls="ls --color"
alias ll="ls -la"


alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cdgit="cd /home/vagrant/host-home/Documents/GitHub/"

alias wow="git status"
alias much="git"

alias deploy="ansible-playbook /home/vagrant/vagrant-desktop/ansible/playbook.yml --tags Deploy"
alias deployall="ansible-playbook /home/vagrant/vagrant-desktop/ansible/playbook.yml"


# add local bin to path
export PATH=~/bin:$PATH
# export vim as editor
export EDITOR=vim

[ -e ~/.dircolors ] && eval $(dircolors -b ~/.dircolors) || eval $(dircolors -b)

source ${ZDOTDIR:-$HOME}/git-prompt/zshrc.sh
# an example prompt
PROMPT='%B%m%~%b$(git_super_status) %# '


