#aliases

# fancy completion
autoload compinit && compinit
zstyle ':completion:*' menu select
#zstyle ':completion:*' list-colors ''
RPROMPT="[%T]"

alias ls="ls --color"
alias ll="ls -la"


alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cdgit="cd /home/vagrant/host-home/Documents/GitHub/"

alias wow="git status"
alias much="git"

alias deploy="ansible-playbook /home/vagrant/vagrant-ansible/ansible/playbook.yml --tags UpdateGit,Deploy"
alias deployall="ansible-playbook /home/vagrant/vagrant-ansible/ansible/playbook.yml"


# add local bin to path
export PATH=~/bin:$PATH
# export vim as editor
export EDITOR=vim

[ -e ~/.dircolors ] && eval $(dircolors -b ~/.dircolors) || eval $(dircolors -b)

#source ${ZDOTDIR:-$HOME}/git-prompt/zshrc.sh
# an example prompt


#Add Function to see current git branch
git_branch () {
branch_name=`git symbolic-ref --quiet --short HEAD 2> /dev/null`
    if [ $? -eq 0 ]
    then
        echo " %F{magenta}$branch_name%f "
    fi
}

setopt PROMPT_SUBST

PROMPT='%B%m%~%b$(git_branch) %# '
