# fancy completion
autoload compinit && compinit
zstyle ':completion:*' menu select
#zstyle ':completion:*' list-colors ''


##aliases
alias ls="ls --color"
alias ll="ls -la"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cdgit="cd /home/vagrant/host-home/Documents/GitHub/"

alias wow="git status"
alias much="git"

alias deploy="ansible-playbook /home/vagrant/vagrant-ansible/ansible/playbook.yml --tags UpdateGit,Deploy"
alias deployall="ansible-playbook /home/vagrant/vagrant-ansible/ansible/playbook.yml"


## add local bin to path
export PATH=~/bin:$PATH
export PATH=~/.local/bin:$PATH
## export vim as editor
export EDITOR=vim

##Use Different Colors for Directory
[ -e ~/.dircolors ] && eval $(dircolors -b ~/.dircolors) || eval $(dircolors -b)


##Add Function to see current git branch
git_branch () {
branch_name=`git symbolic-ref --quiet --short HEAD 2> /dev/null`
    if [ $? -eq 0 ]
    then
        echo " %F{magenta}$branch_name%f "
    fi
}


##set this to get the git_branch function working
setopt PROMPT_SUBST

##Show Time on right side
RPROMPT="[%T]"

##Left Prompt Customization
PS1='[%F{yellow}%m%f:%F{blue}%1~%f]$(git_branch)%# '
